### ISSUE TITLE
undefined method `metrics' for Credentials

### ISSUE THREAD

**Issue by nartz** [aws/aws-sdk-ruby#3277]
### Describe the bug
```
gems/aws-sdk-core-3.227.0/lib/aws-sdk-core/plugins/sign.rb:58:in `with_metrics': undefined method `metrics' for #<Credentials>
```
After upgrading from aws-sdk-core 3.222.1 to 3.227.0 we are now getting this error. 

Is it required now to implement a 'metrics' method on credential provider? This commit seemed to previously check for existence of metrics method prior to trying to execute it [https://github.com/aws/aws-sdk-ruby/commit/da47b00d314df84a9f14dcc2f74b06ebe87f4789#diff-66241a4430dc3ddf6c870d8f2[…]71804f9bcad61927fb6dcc67860aL61](https://github.com/aws/aws-sdk-ruby/commit/da47b00d314df84a9f14dcc2f74b06ebe87f4789#diff-66241a4430dc3ddf6c870d8f2b04bd2a319e71804f9bcad61927fb6dcc67860aL61)

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

Should not throw this error unless metrics is a required method

### Current Behavior

Errors 

### Reproduction Steps

Create a minimal credentials provider class wrapper without metrics function

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core sign.rb

### Environment details (Version of Ruby, OS environment)

ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-darwin22]

**Comment by mullermp** [comment]
Thanks for opening an issue. Do you have a custom credential provider implementation? If you include the `Aws::CredentialProvider` module, it should work.

**Comment by nartz** [comment]
That worked, thank you for the quick response!

**Comment by nartz** [comment]
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CredentialProvider.html could be updated to reflect the need for the 'metrics' method @mullermp

**Comment by mullermp** [comment]
It's API private. Let me think about it. The intention is for credential provider implementations to include the module, so we probably just want to ensure the documentation says that.

**Comment by mullermp** [comment]
I have a small PR for the documentation to state that it should implement and include that module.
