### ISSUE TITLE
Regression in block_device_mappings

### ISSUE THREAD

**Issue by pmenglund** [aws/aws-sdk-ruby#170]
Since I upgraded to 1.8.1.3 I get the following error when accessing the block_device_mappings of an image:

```
[15] pry(main)> ami = ec2.images["ami-807cefe9"]
=> <AWS::EC2::Image id:ami-807cefe9>
[16] pry(main)> ami.block_device_mappings
NoMethodError: undefined method `ebs' for {:device_name=>"/dev/sdb", :virtual_name=>"ephemeral0"}:Hash
from /home/menglund/.rbenv/versions/1.9.3-p374/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.1.3/lib/aws/core/data.rb:101:in `method_missing'
```
