### ISSUE TITLE
Multipart Upload by `S3::FileUploader#upload` causes NoMethodError since v1.200.0

### ISSUE THREAD

**Issue by mtgto** [aws/aws-sdk-ruby#3312]
### Describe the bug

When we update aws-sdk-s3 to v1.200.0 in our system, it crashed while uploading a large file.
We found that the `Aws::S3::Uploader#upload`requires executor as an option, and instance of DefaultExecutor is not used when omitted since aws-sdk-s3 v1.200.0.

https://github.com/aws/aws-sdk-ruby/pull/3302
https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/CHANGELOG.md#12000-2025-10-15

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Successfully upload more than 100MB.
(The Executor automatically uses the `DefaultExecutor`.)

### Current Behavior

Caused NoMethodError in `Aws::S3::MultipartFileUploader#upload_with_executor`
https://github.com/aws/aws-sdk-ruby/blob/b3b9f0645a0eb7d3af7da27314e84a7c112c3e59/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb#L152

```
NoMethodError
undefined method 'post' for nil (NoMethodError)

          @executor.post(part) do |p|
                   ^^^^^
```

### Reproduction Steps

Our code snippets.

```ruby
def self.multipart_upload(source:, bucket:, key:, delivered_file:)
  Aws::S3::FileUploader.new.upload(
    source,
    bucket: bucket,
    key: key,
    content_type: "binary/octet-stream",
    content_disposition: "attachment; filename*=UTF-8''#{delivered_file.encoded_filename}"
  )
end
```

### Possible Solution

Downgrade to v1.199.1.
https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/CHANGELOG.md#11991-2025-09-25

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

ruby 3.4.7

**Comment by jterapin** [comment]
Hi @mtgto,

I apologize for the breaking changes in our update. `Aws::S3::FileUploader` is a private API so that is why we felt safe to make changes since the public entry points are the Object class and Transfer Manager.  I recommend one of the following approaches:

**Option 1 - Use Transfer Manager (most recommended)**
This is a high-level S3 transfer utility. If no executor is provided during initialization, it creates a new DefaultExecutor for each operation. Based on your code, you could implement this:
```ruby
def self.multipart_upload(source:, bucket:, key:, delivered_file:)
  # Consider setting :multipart_threshold if your files are smaller
  # than 100MB (default threshold) to leverage multipart uploads
  Aws::S3::TransferManager.new.upload_file(
    source,
    bucket: bucket,
    key: key,
    content_type: "binary/octet-stream",
    content_disposition: "attachment; filename*=UTF-8''#{delivered_file.encoded_filename}"  
  )
end
```

**Option 2 - Explicitly pass executor**
You can continue using `Aws::S3::FileUploader`, but since it's a private API, I cannot guarantee future compatibility:
```ruby
def self.multipart_upload(source:, bucket:, key:, delivered_file:)
  Aws::S3::FileUploader.new.upload(
    source,
    bucket: bucket,
    key: key,
    content_type: "binary/octet-stream",
    content_disposition: "attachment; filename*=UTF-8''#{delivered_file.encoded_filename}",
    executor: Aws::S3::DefaultExecutor.new
  )
end
```
Please let me know if you have any questions or need further assistance.

**Comment by mtgto** [comment]
@jterapin Thank you for your reply.
I'm sorry I didn't realize FileUploader was marked as a private API 🙇 

We has been modified our source code to use TransferManager instead of FileUploader, and we have confirmed that the problem no longer occurs 👌

**Comment by jterapin** [comment]
Great! I'll close this issue but feel free to let us know if you have any questions.
