### ISSUE TITLE
Aws::SSM::Errors::ParameterNotFound#message returns a class instead of a string

### ISSUE THREAD

**Issue by lenon** [aws/aws-sdk-ruby#2643]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

Hi!

When I call `.message` on an instance of `Aws::SSM::Errors::ParameterNotFound`, I expect to get a string, but I'm getting an `Aws::SSM::Errors::ParameterNotFound` class instead:

```ruby
require 'aws-sdk-ssm'

client = Aws::SSM::Client.new
begin
  client.get_parameter(name: '/path/to/key')
rescue => e
end

puts e.class # => Aws::SSM::Errors::ParameterNotFound
puts e.message # => Aws::SSM::Errors::ParameterNotFound
puts e.message.is_a?(String) # => false
puts e.message == Aws::SSM::Errors::ParameterNotFound # => true
```

This is unexpected because `Exception#message` should return a string in Ruby. Also according to the documentation I should get a string here: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SSM/Errors/ParameterNotFound.html#message-instance_method

This caused an internal error in our error monitoring tool (Sentry):

```
NoMethodError (undefined method `byteslice' for Aws::SSM::Errors::ParameterNotFound:Class)
```

I was able to workaround this issue, but I believe it's a bug and a string should be returned.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

```
aws-sdk-ssm (1.128.0)
```

**Version of Ruby, OS environment**

```
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
```

**Comment by alextwoods** [comment]
Thanks for raising this - I agree this looks like it may be a bug - I'm investigating.

**Comment by alextwoods** [comment]
It looks like this behavior was introduced in #2416.  I believe this should potentially be changed to `self.class.to_s` instead. I'm checking to see to see if there are any possible issues with that change.

**Comment by lenon** [comment]
Thanks, @alextwoods!
