### ISSUE TITLE
DynamoDB: #map on PagableResponse does not work in v2.1.0

### ISSUE THREAD

**Issue by hoffi** [aws/aws-sdk-ruby#842]
Since Version 2.1.0 i cannot use `#map` to get all items from a PagableResponse.

Here is an example of what i use:
```ruby
require 'aws-sdk'
client = Aws::DynamoDB::Client.new(region: 'eu-west-1')

result = client.query(table_name: 'users', index_name: 'username_index', 
                      key_condition_expression: 'user_name = :name',
                      expression_attribute_values: { ':name' => 'test' })

result.map { |page| page.items }
```

Exception: 
```
NoMethodError: undefined method `each' for #<Aws::DynamoDB::Types::QueryOutput:0x007f823b374668>
        from /usr/local/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.0/lib/seahorse/client/response.rb:79:in `map'
        from /usr/local/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.0/lib/seahorse/client/response.rb:79:in `method_missing'
```

`.each.map` however works. In Version 2.0.48 this works without the `each`
Is this intended?

**Comment by trevorrowe** [comment]
It looks like Enumerable was not getting added to the pageable response object in v2.1.0. Thank you for reporting the issue. I've added a test to cover the inclusion of the Enumerable to ensure this does not regress again. I'll try to cut a maintenance release soon.
