### ISSUE TITLE
Loading issues persist with Sidekiq after upgrade to v3

### ISSUE THREAD

**Issue by shoja** [aws/aws-sdk-ruby#1928]
### Issue description
I was seeing an issue with loading certain constants (specifically, `uninitialized constant Aws::S3::Resource`) intermittently in Sidekiq with v2. I upgraded to v3 with the understanding that these issues should be mitigated by the new `require` strategy as indicated by the deprecation of `eager_autoload!`. However, we are still seeing that issue as well as a new one where only certain methods are available on the `Aws::S3::Object`. Specifically, when we go to upload file we get `undefined method 'upload_file'`. 

It doesn't happen every time, but often enough that at our volume we are seeing one or both issues several times a day.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk 3.0.1
aws-sdk-s3 1.23.1

We also kept the default list of service gems when upgrading to v3, but are only really using S3.

### Version of Ruby, OS environment
Ubuntu 16.04.2
Ruby 2.2.5p319
Sidekiq 4.1.4

### Code snippets / steps to reproduce
Our upload calls look like this:
```
obj = s3.bucket(S3_BUCKET).object(archive_key)
obj.upload_file(temp.path, acl: "public-read")
```

The results of calling `.methods` on the `Aws::S3::Object` that we get back from `.object` are significantly different in the "good" cases where the upload succeeds and the "bad" cases where the method is undefined: https://gist.github.com/shoja/71bba9905a7a5f962acff8dce85b2e06

Was my assumption that this was the type of problem addressed by the upgrade to v3 incorrect? Are there other mitigations that we could attempt to solve this issue?

Any guidance or suggestions are greatly appreciated.

**Comment by srchase** [comment]
@shoja 

Are you able to update to the latest version of aws-sdk-s3 and Sidekiq?

The aws-sdk-s3 version is fairly recent, but I understand that that version of Sidekiq is a bit older and upgrading might be more involved.

I'm curious if you get the same behavior with a more recent version of Sidekiq.

**Comment by srchase** [comment]
Closing this issue for inactivity.
