### ISSUE TITLE
Cannot assign metadata to S3 object through S3Object#write(data, options = {})

### ISSUE THREAD

**Issue by matuag** [aws/aws-sdk-ruby#575]
AWS SDK for Ruby version: 1.47.0

Assigning metadata to S3 object using metadata hash in options param of S3Object#write works fine with version 1.46.0 of SDK, but after updating to 1.47.0 it has stopped working.

```
# Options hash
options = {
  bucket_name: 'bucket_name',
  cache_control: 'public, max-age=28800',
  content_type: 'content_type',
  metadata: {
    company: 'ABCXYZ Ltd',
    uploaded: Time.now.utc
  }
}

# Error
undefined method `start_with?' for :company:Symbol
```
