### ISSUE TITLE
Aws::S3::MultipartUploadError when sending large files AND using KMS (works in v 2.1.28)

### ISSUE THREAD

**Issue by danlherman** [aws/aws-sdk-ruby#949]
Got the following error:

aws-sdk-resources-2.1.26/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:72:in `abort_upload': multipart upload failed: undefined method `match' for nil:NilClass (Aws::S3::MultipartUploadError)

The method works with smaller files, or on the same large file (5.9gb) when sent without KMS. This issue does NOT happen using v 2.1.28, but does happen on 2.1.29 and 2.1.26.

Used the following code:

#!/usr/bin/env ruby
require 'aws-sdk'
kms_key = 'xxxxxxxx'
s3 = Aws::S3::Resource.new(
  credentials: Aws::Credentials.new('xxxxxxx', 'xxxxxxxx'),
  region: 'us-east-1'
)
obj = s3.bucket('bucket-name').object('path/to/file.zip')
obj.upload_file('file.zip',  server_side_encryption: 'aws:kms', ssekms_key_id: kms_key)

**Comment by danlherman** [comment]
Sorry, it seems to happen on 2.1.28 with some larger files as well. Just tried sending a 48gb file and after a while got this error:

aws-sdk-resources-2.1.28/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:72:in `abort_upload': multipart upload failed: undefined method `match' for nil:NilClass (Aws::S3::MultipartUploadError)

**Comment by trevorrowe** [comment]
Thank you for reporting this issue. We are looking into it now.

**Comment by trevorrowe** [comment]
Do you know the region of the target bucket? Also, would it be possible for you to rescue the `Aws::S3::MultipartUploadError` for some additional debug information. The upload works by uploading parts using multiple threads. If any of those threads generate errors, then they are aggregated and raised. You can access the original errors from the MPU error:

```ruby
begin
  # ...
rescue Aws::S3::MultipartUploadError => mpu_error
  mpu_error.errors.each do |error|
    puts error.message
    puts error.backtrace
  end
end
```

I think the issue is related signing the upload part requests. When using server side encryption with KMS the request must be signed with signature version 4. There is code in the SDK to rescue the error that indicates this and then attempts to resign and send the request. Its a bit tricky because the SDK must determine the region of the target bucket to generate the version 4 signature.

My best guess is that the code for determining the bucket region is failing to handle when the bucket location is not available as a header. A stack trace might help to confirm this.

I'm also looking into some other alternatives for handling bucket region issues.

**Comment by awood45** [comment]
I managed to recreate this using a ~5 GB file. I'm looking in to it, but for reference here is my stack trace:

```
undefined method `match' for nil:NilClass
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_request_signer.rb:212:in `region_from_location_header'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_request_signer.rb:194:in `detect_region_and_retry'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_request_signer.rb:157:in `handle_region_errors'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_request_signer.rb:150:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_request_signer.rb:33:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_request_signer.rb:124:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_md5s.rb:33:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/rest/handler.rb:7:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/seahorse/client/request.rb:70:in `send_request'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.30/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/alexwood/.rvm/gems/ruby-2.1.1/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:110:in `block (2 levels) in upload_in_threads'
```

**Comment by awood45** [comment]
Essentially, we can confirm that Trevor's gut instinct on this was correct. We're failing when we cannot identify the bucket region from a header. We'll move on to proposing a fix now.

**Comment by awood45** [comment]
As a workaround while we develop the fix for this, you can get this working by using a SigV4 client:

```ruby
s3 = Aws::S3::Client.new(signature_version: 'v4')
```
In my script reproducing your error, this solved the problem.

**Comment by danlherman** [comment]
This worked for me as well!

Aws::S3::Resource.new(
  credentials: Aws::Credentials.new('xxxxx', 'xxxxxx'),
  region: 'us-east-1',
  signature_version: 'v4'
)

**Comment by awood45** [comment]
That's pretty much the full fix too, we're going to make SigV4 the default behavior for all regions with S3. The remaining work has to do with ensuring we don't create any regressions in doing so, but the functionality for your case will be identical.

Still, leaving this open until the root cause is resolved and the fix released.

**Comment by awood45** [comment]
We've pushed the fix for this, and it will go out with the next release. Please let me know if you see a recurrence (unlikely if the workaround has worked for you).
