### ISSUE TITLE
bug in v2.1.x? in revoke_security_group_ingress

### ISSUE THREAD

**Issue by eniskonuk** [aws/aws-sdk-ruby#881]
I'm getting the following exception when using 2.1.4 & 2.1.8 that works fine in 2.0.47. Any insight?

NoMethodError/undefined method `each' for #<Aws::EC2::Types::UserIdGroupPair:0x007fc086830920>

Here is the full stack trace:
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:23:in `structure'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:44:in `format'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:37:in `block in list'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:36:in `each'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:36:in `with_index'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:36:in `list'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:45:in `format'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:26:in `block in structure'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:23:in `each'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:23:in `structure'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:44:in `format'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:37:in `block in list'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:36:in `each'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:36:in `with_index'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:36:in `list'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:45:in `format'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:26:in `block in structure'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:23:in `each'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:23:in `structure'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/ec2_param_builder.rb:16:in `apply'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/protocols/ec2.rb:9:in `apply_params'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/handler.rb:42:in `build_request'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/query/handler.rb:26:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/endpoint.rb:34:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/seahorse/client/logging/handler.rb:10:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/seahorse/client/plugins/response_target.rb:18:in `call'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/seahorse/client/request.rb:70:in `send_request'
/Users/eniskonuk/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/aws-sdk-core-2.1.4/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/eniskonuk/qwiklab/deploy/tools/v2cleaning/aws/ec2.rb:383:in `revoke_secgrp'

**Comment by trevorrowe** [comment]
Thank you for reporting this issue.

There was a regression in serializing structure data types. The shared protocol tests exercised all of the code-paths of the param builder, but did not test with structure data types as input. This was was being tested for the other builder classes via their unit tests. I added a spec file for the EC2 param builder and added a test to cover this regression.

Sorry for the inconvenience. This fix should be released shortly.

**Comment by eniskonuk** [comment]
Thanks @trevorrowe
